"""add unique constraints and onupdate trigger"""

revision = '22f0f36b26f8'
down_revision = 'e3cfe1e6bb56'
branch_labels = None
depends_on = None

from alembic import op



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_complaint_ownership_complaint_id', 'complaint_ownership', ['complaint_id'])
    op.create_unique_constraint('uq_student_subject', 'student_subjects', ['student_email', 'subject_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_student_subject', 'student_subjects', type_='unique')
    op.drop_constraint('uq_complaint_ownership_complaint_id', 'complaint_ownership', type_='unique')
    # ### end Alembic commands ###
